blank_issues_enabled: false
contact_links:
- name: '📚 Create an Issue'
  about: Create an issue if something does not work as expected or if you need to suggest adding new functionality.
  url: https://github.com/wso2/product-apim/issues/new/choose
- name: '💬 Slack Channel'
  url: 'https://apim-slack.wso2.com/'
  about: |
    Chat with the community to get quick clarifications for your questions.
